# Generated by Django 3.1.4 on 2020-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='userCart_set',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(through='ecommerce.CartObj', to='ecommerce.Product'),
        ),
    ]
