# Generated by Django 3.1.4 on 2020-12-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20201219_1852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderobj',
            unique_together={('order', 'product')},
        ),
    ]
