# Generated by Django 3.1.4 on 2020-12-19 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20201219_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
