# Generated by Django 3.1.4 on 2020-12-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('JEWELLERY', 'Jewellery'), ('CLOTH', 'Cloth')], max_length=50),
        ),
    ]
