# Generated by Django 3.1.4 on 2020-12-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20201217_2140'),
        ('ecommerce', '0005_auto_20201218_1329'),
    ]

    operations = [
    ]
