# Generated by Django 3.1.4 on 2020-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20201220_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
