# Generated by Django 3.1.4 on 2020-12-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_photo'),
        ('ecommerce', '0007_auto_20201221_1326'),
        ('ecommerce', '0007_like'),
    ]

    operations = [
    ]
