# Generated by Django 3.1.4 on 2020-12-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20201222_1316'),
        ('ecommerce', '0010_auto_20201222_1453'),
    ]

    operations = [
    ]
