# Generated by Django 3.1.4 on 2021-01-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20201229_1038'),
        ('ecommerce', '0012_auto_20201229_0909'),
    ]

    operations = [
    ]
