# Generated by Django 3.1.4 on 2020-12-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20201229_0909'),
        ('ecommerce', '0012_auto_20201229_1038'),
    ]

    operations = [
    ]
