# Generated by Django 3.1.4 on 2021-01-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210107_1818'),
        ('ecommerce', '0014_review_created_on'),
    ]

    operations = [
    ]
