# Generated by Django 3.1.4 on 2021-01-16 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_review_created_on'),
        ('ecommerce', '0015_appointment'),
    ]

    operations = [
    ]
